#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 24 15:03:58 +07 2026
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_mips_top_behav -key {Behavioral:sim_1:Functional:tb_mips_top} -tclbatch tb_mips_top.tcl -view /home/legion/Desktop/MIPS/tb_mips_top_behav.wcfg -log simulate.log"
xsim tb_mips_top_behav -key {Behavioral:sim_1:Functional:tb_mips_top} -tclbatch tb_mips_top.tcl -view /home/legion/Desktop/MIPS/tb_mips_top_behav.wcfg -log simulate.log

